// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: header.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Scnet_Header {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var packetType: UInt32 = 0

  public var reqCb: Int32 = 0

  public var resCb: Int32 = 0

  public var authToken: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "scnet"

extension Scnet_Header: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Header"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "packetType"),
    2: .standard(proto: "req_cb"),
    3: .standard(proto: "res_cb"),
    4: .same(proto: "authToken"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularUInt32Field(value: &self.packetType)
      case 2: try decoder.decodeSingularInt32Field(value: &self.reqCb)
      case 3: try decoder.decodeSingularInt32Field(value: &self.resCb)
      case 4: try decoder.decodeSingularUInt32Field(value: &self.authToken)
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.packetType != 0 {
      try visitor.visitSingularUInt32Field(value: self.packetType, fieldNumber: 1)
    }
    if self.reqCb != 0 {
      try visitor.visitSingularInt32Field(value: self.reqCb, fieldNumber: 2)
    }
    if self.resCb != 0 {
      try visitor.visitSingularInt32Field(value: self.resCb, fieldNumber: 3)
    }
    if self.authToken != 0 {
      try visitor.visitSingularUInt32Field(value: self.authToken, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Scnet_Header, rhs: Scnet_Header) -> Bool {
    if lhs.packetType != rhs.packetType {return false}
    if lhs.reqCb != rhs.reqCb {return false}
    if lhs.resCb != rhs.resCb {return false}
    if lhs.authToken != rhs.authToken {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
